<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Reseller extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name',
        'email',
        'password',
        'balance',
        'balance_spent',
        'profit',
        'discount_percentage',
    ];

    protected $hidden = [
        'password',
    ];

    protected $casts = [
        'balance' => 'decimal:2',
        'balance_spent' => 'decimal:2',
        'profit' => 'decimal:2',
        'discount_percentage' => 'decimal:2',
    ];

    /**
     * Calculate final price with discount
     */
    public function calculatePrice(float $basePrice): float
    {
        $discount = ($basePrice * $this->discount_percentage) / 100;
        return $basePrice - $discount;
    }

    /**
     * Check if reseller can afford a license
     */
    public function canAfford(float $price): bool
    {
        return $this->balance >= $price;
    }

    /**
     * Deduct amount from balance
     */
    public function deductBalance(float $amount): void
    {
        $this->balance -= $amount;
        $this->save();
    }

    /**
     * Add amount to balance
     */
    public function addBalance(float $amount): void
    {
        $this->balance += $amount;
        $this->save();
    }

    /**
     * Track balance spent and calculate profit
     */
    public function trackPurchase(float $discountedPrice, float $fullPrice): void
    {
        $this->balance_spent += $discountedPrice;
        $this->profit += ($fullPrice - $discountedPrice);
        $this->save();
    }

    /**
     * License keys generated by this reseller
     */
    public function licenseKeys()
    {
        return $this->hasMany(LicenseKey::class, 'reseller_id');
    }
}
